-- I Am Omani persistent player accounts
-- Run this on the dedicated Supabase project for the game.

create table if not exists public.player_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  phone text not null unique,
  display_name text,
  avatar text default '🇴🇲',
  xp integer not null default 0 check (xp >= 0),
  level integer not null default 1 check (level >= 1),
  level_name text not null default 'مستكشف عُمان',
  games integer not null default 0,
  wins integer not null default 0,
  correct_answers integer not null default 0,
  fastest_answers integer not null default 0,
  best_streak integer not null default 0,
  current_streak integer not null default 0,
  perfect_games integer not null default 0,
  badges jsonb not null default '[]'::jsonb,
  category_stats jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint username_format check (username ~ '^[A-Za-z0-9_]{3,24}$')
);

create table if not exists public.player_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_type text not null,
  category text,
  xp_delta integer not null default 0,
  room_code text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists player_activity_user_idx on public.player_activity(user_id, created_at desc);

alter table public.player_profiles enable row level security;
alter table public.player_activity enable row level security;

create policy "profiles readable by authenticated users"
on public.player_profiles for select
to authenticated
using (true);

create policy "users update own profile"
on public.player_profiles for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users insert own profile"
on public.player_profiles for insert
to authenticated
with check (auth.uid() = user_id);

create policy "users read own activity"
on public.player_activity for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.player_profiles(user_id, username, phone, display_name)
  values (
    new.id,
    lower(coalesce(new.raw_user_meta_data->>'username','player_' || substr(new.id::text,1,8))),
    coalesce(new.raw_user_meta_data->>'phone',''),
    coalesce(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'username')
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.touch_player_profile()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_player_profile on public.player_profiles;
create trigger trg_touch_player_profile
before update on public.player_profiles
for each row execute procedure public.touch_player_profile();
